olimpiu_crisan:
    resource: "@OlimpiuCrisanBundle/Controller/"
    type:     annotation
    prefix:   /OlimpiuCrisan

coman_ionut:
    resource: "@ComanIonutBundle/Resources/config/routing.yml"
    prefix:   /coman-ionut

pabd2_buzenco:
    resource: "@PABD2BuzencoBundle/Controller/"
    type:     annotation
    prefix:   /buzenco

blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /

adauga_adaugau:
    resource: "@AdaugaAdaugauBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_routes:
    resource: "@BloggerBlogBundle/Controller"
    type: annotation

admin:
    path:      /admin
    defaults:  { _controller: AppBundle:Admin:index }

adaugau:
    path: /adaugau
    defaults: {_controller: AdaugaAdaugauBundle:Adaugau:adauga}

despre_camelia:
    path: /despre_camelia
    defaults: {_controller: AppBundle:DespreCamelia:indexcamelia}

despre_ordace:
    path: /despre_ordace
    defaults: {_controller: AppBundle:DespreOrdace:indexordace}
fani:
    resource: "@faniBundle/Resources/config/routing.yml"
    prefix:   /
palaghiaandrei:
    path: /palaghiaandrei
    defaults: {_controller: AppBundle:DespreAndrei:indexandrei}
adaugafani:
    path: /adaugafani
    defaults: {_controller: faniBundle:AdaugaFani:adaugafani}  

inserare_inserarea:
    resource: "@InserareInserareaBundle/Resources/config/routing.yml"
    prefix:   /

inserare_admin:
    path: /inserare_admin
    defaults: {_controller: InserareInserareaBundle:Inserarea:inserare}
